config/routes.rb
Rails.application.routes.draw do
  resources :subastas
  resources :homes
  get 'adm',to: 'adm#index'
  root 'main#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/subasta.rb
class Subasta < ApplicationRecord
end

app/controllers/adm_controller.rb
class AdmController < ApplicationController
  def index
	@homes=Home.all
  end

  def show
  end
  
  def ver    
  end
  
  def destroy
    monstruo = Monstruo.find(params[:id])
    monstruo.destroy
    redirect_to monstruos_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def edit
  	@home=Home.find(params[:id])	
  end
  def update
  	@home=Home.find(params[:id])
     if @home.update(params.require(:home).permit(:nombre))
  		redirect_to adm_path
     else
		render :edit
	end	
  end
  def new 
  	@home=Home.new
  end
  def create
 	@home=Home.new(params.require(:home).permit(:nombre,:ubicacion,:disponibilidad))
 	if @home.save
 		redirect_to adm_path
 	else
 		render :new
 	end
  end
  
  def default
    
  end
  
  def index
     @homes=Home.all
  end

  def show
  end
  def destroy
	@home=Home.find(params[:id])
  	if @home.destroy
		redirect_to adm_path
	else
		redirect_to adm_path
 	end 
 end
end

app/controllers/subastas_controller.rb
class SubastasController < ApplicationController
  def index
  	 @homes=Home.all
  	 @subasta=Subasta.new
  end
  def create
 	@subasta=Subasta.new(params.require(:subasta).permit(:titulo))
 	if @subasta.save
 		redirect_to adm_path
 	else
 		render :index
 	end
  end
  def new 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adm/index.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">AppAdmin</a>
        </div>
      </div>
    </nav>

    <section id="main"
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
Residences List</h3>
			</div>
			<div class="panel-body">
				<table class="table table-striped table-hover">
				<tr>
					<th>Nombre</th>
					<th>Ubicacion</th>
					<th>Disponibilidad</th>
				</tr>		
				<% @homes.each do |home| %>
					<tr>
						<td><%= home.nombre%></td>
						<td>
						<%= home.ubicacion%>
						</td>
						<td><%= home.disponibilidad%></td>
						<td><%= link_to "Edit",edit_home_path(home),class: "btn btn-default"%>
						<%= link_to "Delet",home,method: :delete,data:{confirm: "Estas seguro?"},class: "btn btn-default"%>
						</td>
					</tr>
				<%end%>		
				</table>
			</div>
		</div>
    </section>
    <%= link_to "New Residence",new_home_path,class: "btn btn-default"%>
  <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

app/views/homes/_form.html.erb
<%= form_for @home do |f| %>
	<div class="container">
        <div class="panel-body">
          <!-- FORM -->
          <form class="form-horizontal" role="form">
            <div class="form-group">
              <label class="col-sm-3 control-label">Nombre			    </label>
              <div class="col-sm-9">
                <%= f.text_field :nombre, :class => "form-control", :placeholder => "Nombre"%>
		   </div>
		<label class="col-sm-3 control-label">Ubicacion			    </label>
              <div class="col-sm-9">
                <%= f.text_field :ubicacion, :class => "form-control", :placeholder => "Ubicacion"%>
		   </div>
          <label class="col-sm-3 control-label">Disponibilidad			    </label>
              <div class="col-sm-9">
                <%= f.text_field :disponibilidad, :class => "form-control", :placeholder => "Disponibilidad"%>
		   </div>
	    </form>
	</div>
		<div class="form-group last">
	     <div class="col-sm-offset-3 col-sm-9">
		   <%= f.submit 'Guardar',:class => "btn btn-default"%>
		</div>
		</div>
	</div>
<% end %>

app/views/homes/edit.html.erb
<%= render "form" %>

app/views/homes/index.html.erb
<h1>Residencias#index</h1>
<p>Find me in app/views/residencias/index.html.erb</p>

app/views/homes/new.html.erb
<%= render "form" %>

app/views/homes/show.html.erb
<h1>Residencias#show</h1>
<p>Find me in app/views/residencias/show.html.erb</p>

app/views/layouts/_header.html.erb
<header>
   
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>AppAdmin | Panel de Control </title>

    <!-- Bootstrap core CSS -->
    <link href="/stylesheets/bootstrap.min.css" rel="stylesheet">
    <link_rel="stylesheet" type="text/css" href="stylesheets/estilos.css">

</head>
<body>
<%= yield %>
</body>
</html>

app/views/main/index.html.erb
<h1> Bienvenido a Critter </h1>

app/views/subastas/index.html.erb
jejrjrjjr

app/views/subastas/show.html.erb
<h1> somos unos capos </h1>